#!/usr/bin/ruby
require 'webrick'
include WEBrick

server = HTTPServer.new(
  :Port            => 4000,
  :DocumentRoot    => Dir::pwd + "/bin"
)
server.mount("/bin", HTTPServlet::FileHandler, Dir::pwd + "/bin")

trap("INT"){ server.shutdown }
server.start